print('Hello, Natalya!')
print('клон из гитхаб в гит')
print('Пробуем push в github')
print('test push')
print('Ура! Все получилось!')
print('Тестим еще раз пуш')
print("И еще разок")
print("Тест")