print('Hello, Natalya!')
print('клон из гитхаб в гит')
print('Пробуем push в github')
print('test push')
print('Ура! Все получилось!')
print('Как добавить с удаленного сервера в локальный?')
print('Hello from GitHub')
print('Заливаем из удаленного в локальный')
print('Заливаем из локального в удаленный')
